[build]
  command = "npm run build"
  publish = "build"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain"

[template.environment]
  REACT_API_URL = "https://resume-analyser-o3eu.onrender.com" 